version: '3.8'

services:
  # База данных
  db:
    image: postgres:15-alpine
    container_name: greenhouse-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=greenhouse
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Твоё Java-приложение
  app:
    build: .
    container_name: greenhouse-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      # ВАЖНО: здесь указываем имя сервиса "db", а не IP
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/greenhouse
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

volumes:
  pg_data: