name: Java CI with Maven

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # Запускаем полную сборку с выполнением всех тестов
      run: mvn -B clean verify  -P full-tests
    
    - name: Add coverage report to PR
      uses: madrapps/jacoco-report@v1.6.1
      if: github.event_name == 'pull_request' # Только для PR
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 80
